name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - webpage-src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source branch
      uses: actions/checkout@v2
      with:
        ref: webpage-src

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U jupyter-book

    - name: Build the Jupyter Book
      run: |
        jupyter-book build AID2E-2024/AID2E-2024

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git clone --branch webpage https://github.com/${{ github.repository }} webpage
        rsync -av --delete _build/html/ webpage/
        cd webpage
        git add .
        git commit -m 'Deploy Jupyter Book'
        git push origin webpage
